### PR TITLE
Cleanup ProcessClusterNodeError after disabling addNodeTag

### PR DESCRIPTION
**Pull request by heypnus**

### CODE REVIEW

**Comment by ggverma** [comment]
Is there an Issue for this?

**Comment by dantingl** [comment]
Is this an update issue that user changes `addNodeTag` from `True` to `False`?

**Review by dantingl — APPROVED** [review]

**Comment by heypnus** [comment]
> Is there an Issue for this?

2692705

**Comment by heypnus** [comment]
> Is this an update issue that user changes `addNodeTag` from `True` to `False`?

yes

**Pull request merged**
